# Generated by Django 5.2.2 on 2025-08-03 07:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReview",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        blank=True, help_text="Rating from 1-5", null=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Override client name for display",
                        max_length=255,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="Client's company name", max_length=255
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Project Review",
                "verbose_name_plural": "Project Reviews",
                "db_table": "project_review",
                "ordering": ["-date_created"],
            },
        ),
        migrations.AddField(
            model_name="projectcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="projects.projectcomment",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcomment",
            index=models.Index(
                fields=["parent_comment"], name="project_com_parent__2d614a_idx"
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "client"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="project",
            field=models.ForeignKey(
                limit_choices_to={"status": "completed"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["project"], name="project_rev_project_775bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["client"], name="project_rev_client__ae266f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["featured"], name="project_rev_feature_80a13d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["approved"], name="project_rev_approve_3121c9_idx"
            ),
        ),
    ]
