# Generated by Django 5.2.2 on 2025-08-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectreview_projectcomment_parent_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectreview",
            name="client",
        ),
        migrations.RemoveField(
            model_name="projectreview",
            name="project",
        ),
        migrations.RemoveIndex(
            model_name="projectcomment",
            name="project_com_parent__2d614a_idx",
        ),
        migrations.RemoveField(
            model_name="projectcomment",
            name="parent_comment",
        ),
        migrations.DeleteModel(
            name="ProjectReview",
        ),
    ]
