# Generated by Django 5.2.2 on 2025-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="route_name",
            field=models.CharField(
                default="home",
                help_text="Route name for this hero section (e.g., 'home', 'projects', 'about')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only one hero section should be active per route",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="herosection",
            unique_together={("route_name", "is_active")},
        ),
    ]
