# Generated by Django 5.2.2 on 2025-08-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_herosection_route_name_alter_herosection_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="herosection",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only one hero section should be active at a time",
            ),
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="route_name",
        ),
    ]
