# Generated by Django 5.2.2 on 2025-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Has the user's email been verified?"
            ),
        ),
    ]
