# Generated by Django 5.2.2 on 2025-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.URLField(
                blank=True,
                help_text="Profile image URL (Google or uploaded)",
                null=True,
            ),
        ),
    ]
