# Generated by Django 5.2.2 on 2025-08-03 14:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("social_media", "Social Media"),
                            ("referral", "Referral"),
                            ("manual", "Manual"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("emails_sent", models.IntegerField(default=0)),
                ("emails_opened", models.IntegerField(default=0)),
                ("last_email_opened", models.DateTimeField(blank=True, null=True)),
                (
                    "date_subscribed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_unsubscribed", models.DateTimeField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "db_table": "newsletter_subscriber",
                "ordering": ["-date_subscribed"],
                "indexes": [
                    models.Index(fields=["email"], name="newsletter__email_c1e80c_idx"),
                    models.Index(
                        fields=["status"], name="newsletter__status_c9941b_idx"
                    ),
                    models.Index(
                        fields=["source"], name="newsletter__source_a49e19_idx"
                    ),
                    models.Index(
                        fields=["date_subscribed"],
                        name="newsletter__date_su_28c3e8_idx",
                    ),
                ],
            },
        ),
    ]
