# Generated by Django 5.2.2 on 2025-08-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_newslettersubscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]
